### PR TITLE
chore(main): release 1.1.4

### PR DESCRIPTION
**Pull request by tobiasdiez**
:robot: I have created a release *beep* *boop*
---

### 🧹 Miscellaneous

* widen admissable version range for peer dependency h3 ([0ce0ce4](https://github.com/apollo-server-integrations/apollo-server-integration-h3/commit/0ce0ce4dfb88abff4d9cb431e0c073c7272552e4))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by trevor-scheer** [comment]
This should be a major release, no? @tobiasdiez

**Comment by tobiasdiez** [comment]
h3 (along with some other related packages) went to "stable", because of the release of nuxt 3 tomorrow. I don't know if we should jump on this train as well. Or did you had another reason for major release in mind?

**Comment by trevor-scheer** [comment]
@tobiasdiez narrowing a peer dependency (like dropping support for a lower range) would be a breaking change (and so a major).

In order for this to be a minor, I'd expect the peer deps to be only _widened_ like so:
`"h3": "^0.8.6 || ^1.0.0"`

(assuming this package can run with either of those versions, which I believe it can given that there were no changes required on #19 that upgraded the dependency)

**Comment by trevor-scheer** [comment]
Relatedly, you might add the related renovate extension to your config:
https://docs.renovatebot.com/presets-default/#widenpeerdependencies

**Comment by tobiasdiez** [comment]
@trevor-scheer  You are right, of course! I completely missed that h3 is declared as a peer dep. Thanks also for the pointer to the renovate preset.

**Comment by tobiasdiez** [comment]
:robot: Release is at https://github.com/apollo-server-integrations/apollo-server-integration-h3/releases/tag/v1.1.4 :sunflower:

**Pull request merged**
